server:
  port: 8080
spring:
  application:
    name: University
  # datasource? DB? ?? ?? ??? ?? ??.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/web
    url: jdbc:mariadb://mariadb:3306/web
    username: beyond
    password: beyond
mybatis:
  # ???? ?????? ??
  type-aliases-package: com.beyond.university.*.model.vo
  mapper-locations:
    - classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: NULL